### ISSUE TITLE
Compile ALLiveVideoChat Error

### ISSUE THREAD

**Issue by azzahrah** [Zeus64/alcinoe#47]
[Exec Error] The command "PATH C:\Program Files\Java\jdk1.8.0_121\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\tizen-studio\tools\ide\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Roaming\npm & "D:\android\sdk\build-tools\23.0.1\dx.bat" --dex --output="D:\dev\component\alcinoe\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "D:\dev\component\alcinoe\lib\jar\org.webrtc\webrtc.jar"" exited with code 1.

**Comment by azzahrah** [comment]
Try to dex webrtc manually and add dependencies but problem still appear

`Microsoft Windows [Version 10.0.17763.316]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Windows\system32>dex
'dex' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>dx
error: no command specified
usage:
  dx --dex [--debug] [--verbose] [--positions=<style>] [--no-locals]
  [--no-optimize] [--statistics] [--[no-]optimize-list=<file>] [--no-strict]
  [--keep-classes] [--output=<file>] [--dump-to=<file>] [--dump-width=<n>]
  [--dump-method=<name>[*]] [--verbose-dump] [--no-files] [--core-library]
  [--num-threads=<n>] [--incremental] [--force-jumbo] [--no-warning]
  [--multi-dex [--main-dex-list=<file> [--minimal-main-dex]]
  [--input-list=<file>]
  [<file>.class | <file>.{zip,jar,apk} | <directory>] ...
    Convert a set of classfiles into a dex file, optionally embedded in a
    jar/zip. Output name must end with one of: .dex .jar .zip .apk or be a directory.
    Positions options: none, important, lines.
    --multi-dex: allows to generate several dex files if needed. This option is
    exclusive with --incremental, causes --num-threads to be ignored and only
    supports folder or archive output.
    --main-dex-list=<file>: <file> is a list of class file names, classes defined by
    those class files are put in classes.dex.
    --minimal-main-dex: only classes selected by --main-dex-list are to be put in
    the main dex.
    --input-list: <file> is a list of inputs.
    Each line in <file> must end with one of: .class .jar .zip .apk or be a directory.
  dx --annotool --annotation=<class> [--element=<element types>]
  [--print=<print types>]
  dx --dump [--debug] [--strict] [--bytes] [--optimize]
  [--basic-blocks | --rop-blocks | --ssa-blocks | --dot] [--ssa-step=<step>]
  [--width=<n>] [<file>.class | <file>.txt] ...
    Dump classfiles, or transformations thereof, in a human-oriented format.
  dx --find-usages <file.dex> <declaring type> <member>
    Find references and declarations to a field or method.
    declaring type: a class name in internal form, like Ljava/lang/Object;
    member: a field or method name, like hashCode
  dx -J<option> ... <arguments, in one of the above forms>
    Pass VM-specific options to the virtual machine that runs dx.
  dx --version
    Print the version of this tool (1.11).
  dx --help
    Print this message.
C:\Windows\system32>dx --dex --output="D:\webrtc-dexed.jar" "D:\dev\component\alcinoe\lib\jar\org.webrtc\webrtc.jar" "D:\dev\component\alcinoe\lib\jar\org.webrtc\jsr305-3.0.2.jar"

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
        at com.android.dx.command.dexer.Main.processClass(Main.java:752)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
        at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
        at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:672)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
        at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
        at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
        at com.android.dx.command.dexer.Main.processClass(Main.java:749)
        ... 12 more
1 error; aborting
C:\Windows\system32>`

**Comment by azzahrah** [comment]
any one know solve this problem?

Build started 17/03/2019 12:27:30.
__________________________________________________
Project "D:\dev\component\alcinoe\demos\ALLiveVideoChat\client\_source\ALLiveVideoChatClient.dproj" (Make target(s)):
Target BuildPredexedJar:
    PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;D:\android\sdk\build-tools\23.0.1;C:\Program Files\Java\jdk1.7.0_25\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\tizen-studio\tools\ide\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Roaming\npm & "D:\android\sdk\build-tools\28.0.3\dx.bat" --dex --output="D:\dev\component\alcinoe\demos\ALLiveVideoChat\client\Android\Debug\support-annotations-dexed.jar" "D:\dev\component\alcinoe\lib\jar\com.android.support\support-annotations.jar"
    PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;D:\android\sdk\build-tools\23.0.1;C:\Program Files\Java\jdk1.7.0_25\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\tizen-studio\tools\ide\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Roaming\npm & "D:\android\sdk\build-tools\28.0.3\dx.bat" --dex --output="D:\dev\component\alcinoe\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "D:\dev\component\alcinoe\lib\jar\org.webrtc\webrtc.jar"
    WARNING in org.webrtc.CameraSession.getDeviceOrientation:(Landroid/content/Context;)I: defining a static interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.CameraSession.getDeviceOrientation:(Landroid/content/Context;)I
    WARNING in org.webrtc.CameraSession.createTextureBufferWithModifiedTransformMatrix:(Lorg/webrtc/TextureBufferImpl;ZI)Lorg/webrtc/VideoFrame$TextureBuffer;: defining a static interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.CameraSession.createTextureBufferWithModifiedTransformMatrix:(Lorg/webrtc/TextureBufferImpl;ZI)Lorg/webrtc/VideoFrame$TextureBuffer;
    WARNING in org.webrtc.CameraVideoCapturer.addMediaRecorderToCamera:(Landroid/media/MediaRecorder;Lorg/webrtc/CameraVideoCapturer$MediaRecorderHandler;)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.CameraVideoCapturer.addMediaRecorderToCamera:(Landroid/media/MediaRecorder;Lorg/webrtc/CameraVideoCapturer$MediaRecorderHandler;)V
    WARNING in org.webrtc.CameraVideoCapturer.removeMediaRecorderFromCamera:(Lorg/webrtc/CameraVideoCapturer$MediaRecorderHandler;)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.CameraVideoCapturer.removeMediaRecorderFromCamera:(Lorg/webrtc/CameraVideoCapturer$MediaRecorderHandler;)V
    WARNING in org.webrtc.EglBase.create:(Lorg/webrtc/EglBase$Context;[I)Lorg/webrtc/EglBase;: defining a static interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.EglBase.create:(Lorg/webrtc/EglBase$Context;[I)Lorg/webrtc/EglBase;
    WARNING in org.webrtc.EglBase.create:()Lorg/webrtc/EglBase;: defining a static interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.EglBase.create:()Lorg/webrtc/EglBase;
    WARNING in org.webrtc.PeerConnection$Observer.onTrack:(Lorg/webrtc/RtpTransceiver;)V: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.PeerConnection$Observer.onTrack:(Lorg/webrtc/RtpTransceiver;)V
    WARNING in org.webrtc.VideoDecoder.createNativeVideoDecoder:()J: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.VideoDecoder.createNativeVideoDecoder:()J
    WARNING in org.webrtc.VideoDecoderFactory.createDecoder:(Ljava/lang/String;)Lorg/webrtc/VideoDecoder;: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.VideoDecoderFactory.createDecoder:(Ljava/lang/String;)Lorg/webrtc/VideoDecoder;
    WARNING in org.webrtc.VideoDecoderFactory.createDecoder:(Lorg/webrtc/VideoCodecInfo;)Lorg/webrtc/VideoDecoder;: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.VideoDecoderFactory.createDecoder:(Lorg/webrtc/VideoCodecInfo;)Lorg/webrtc/VideoDecoder;
    WARNING in org.webrtc.VideoDecoderFactory.getSupportedCodecs:()[Lorg/webrtc/VideoCodecInfo;: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.VideoDecoderFactory.getSupportedCodecs:()[Lorg/webrtc/VideoCodecInfo;
    WARNING in org.webrtc.VideoEncoder.createNativeVideoEncoder:()J: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.VideoEncoder.createNativeVideoEncoder:()J
    WARNING in org.webrtc.VideoEncoder.isHardwareEncoder:()Z: defining a default interface method requires --min-sdk-version >= 24 (currently 13) for interface methods: org.webrtc.VideoEncoder.isHardwareEncoder:()Z
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.Camera1Session.listenForTextureFrames:()V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.Camera1Session$2.onPreviewFrame:([BLandroid/hardware/Camera;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.Camera2Session.getFrameOrientation:()I: invoking a static interface method org.webrtc.CameraSession.getDeviceOrientation:(Landroid/content/Context;)I strictly requires --min-sdk-version >= 24 (blocked at current API level 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.Camera2Session$CaptureSessionCallback.onConfigured:(Landroid/hardware/camera2/CameraCaptureSession;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.EglBase.create:()Lorg/webrtc/EglBase;: invoking a static interface method org.webrtc.EglBase.create:(Lorg/webrtc/EglBase$Context;[I)Lorg/webrtc/EglBase; strictly requires --min-sdk-version >= 24 (blocked at current API level 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.EglRenderer.init:(Lorg/webrtc/EglBase$Context;[ILorg/webrtc/RendererCommon$GlDrawer;)V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.JavaI420Buffer.allocate:(II)Lorg/webrtc/JavaI420Buffer;: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.MediaCodecVideoDecoder.setEglContext:(Lorg/webrtc/EglBase$Context;)V: invoking a static interface method org.webrtc.EglBase.create:(Lorg/webrtc/EglBase$Context;)Lorg/webrtc/EglBase; strictly requires --min-sdk-version >= 24 (blocked at current API level 13)
    Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in org.webrtc.MediaCodecVideoEncoder.setEglContext:(Lorg/webrtc/EglBase$Context;)V: invoking a static interface method org.webrtc.EglBase.create:(Lorg/webrtc/EglBase$Context;)Lorg/webrtc/EglBase; strictly requires --min-sdk-version >= 24 (blocked at current API level 13)
    
    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.RuntimeException: Translation has been interrupted
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:614)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
    	at com.android.dx.command.dexer.Main.runDx(Main.java:288)
    	at com.android.dx.command.dexer.Main.main(Main.java:244)
    	at com.android.dx.command.Main.main(Main.java:95)
    Caused by: java.lang.InterruptedException: Too many errors
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:606)
    	... 4 more
    c:\program files (x86)\embarcadero\studio\19.0\bin\CodeGear.Common.Targets(887,5): error MSB3073: The command "PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;D:\android\sdk\build-tools\23.0.1;C:\Program Files\Java\jdk1.7.0_25\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\tizen-studio\tools\ide\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Roaming\npm & "D:\android\sdk\build-tools\28.0.3\dx.bat" --dex --output="D:\dev\component\alcinoe\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "D:\dev\component\alcinoe\lib\jar\org.webrtc\webrtc.jar"" exited with code 2.
Done building target "BuildPredexedJar" in project "ALLiveVideoChatClient.dproj" -- FAILED.
Done building project "ALLiveVideoChatClient.dproj" -- FAILED.
Build FAILED.
c:\program files (x86)\embarcadero\studio\19.0\bin\CodeGear.Common.Targets(887,5): error MSB3073: The command "PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;D:\android\sdk\build-tools\23.0.1;C:\Program Files\Java\jdk1.7.0_25\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\tizen-studio\tools\ide\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Roaming\npm & "D:\android\sdk\build-tools\28.0.3\dx.bat" --dex --output="D:\dev\component\alcinoe\demos\ALLiveVideoChat\client\Android\Debug\webrtc-dexed.jar" "D:\dev\component\alcinoe\lib\jar\org.webrtc\webrtc.jar"" exited with code 2.
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:04.49

**Comment by Zeus64** [comment]
can you try again now in Rio with the last source code ?

**Comment by azzahrah** [comment]
I have tried last source code, but  it's the same problem

**Comment by azzahrah** [comment]
Mybe the problem is because webrtc.jar compiled with minimum target 13 since buildtools need minimum 26

**Comment by azzahrah** [comment]
I think problem solved with this options:

dx.bat --dex --min-sdk-version=26 --output="c:\alcinoe-dexe.jar" "d:\dev\component\alcinoe\lib\jar\org.webrtc\webrtc.jar"

**Comment by azzahrah** [comment]
@Zeus64  my be you can back to support android 1.7 by using this library

https://github.com/HuuNguyen312/WebRTC_Android_JDK_7

**Comment by Zeus64** [comment]
ooh yes i see ! you must use \Alcinoe\tools\D8Proxy\dx.bat instead of the original dx.bat located in your sdk path. liveVideoChat require D8.bat but Delphi still not yet use it

**Comment by Svema-svg** [comment]
EN:
Hello, you can record a video of how to properly install your component, on Sydney 10_4_2
many people have problems installing
it would be very useful for others

RU:
Здравствуйте, вы можете записать видео как правильно установить ваш компонент, на Сидней 10_4_2
у многих людей возникают проблемы с установкой
это было бы очень полезно для других

**Comment by Zeus64** [comment]
What trouble do you have exactly ?

**Comment by Svema-svg** [comment]
![1](https://user-images.githubusercontent.com/71798557/120820911-a113ec80-c55d-11eb-87d7-270f5e4bea66.jpg)

**Comment by Svema-svg** [comment]
![2](https://user-images.githubusercontent.com/71798557/120822381-061c1200-c55f-11eb-85b6-cbe9632d42cd.jpg)

**Comment by Zeus64** [comment]
Hmm, ok it's update.bat that fail :(
with version of GIT do you have ?

**Comment by Svema-svg** [comment]
Hi, I still managed to compile an example of Live VideoChat (Client) and get a working. apk
But what I want to say:
this command does not allow GIT to patch the copied files,
but if Update.bat run from the root of the component itself, then GIT patches everything correctly and there are no errors
for other people the component can be located on different paths, hence the errors with the GIT command
![1](https://user-images.githubusercontent.com/71798557/120902421-042e7d80-c649-11eb-8230-89acf4cef589.jpg)

**Comment by Svema-svg** [comment]
second:
in the dx file.bat you need to specify your correct paths

**Comment by Svema-svg** [comment]
so:
1. Your Update.bat should do everything without errors
2. in the dx file.bat you must specify your correct paths
3. copy the dx.bat with replacement(as written in the installation instructions)
4. After all this, the Live VideoChat (Client) example should compile well and without errors
----------------------------------------
![1](https://user-images.githubusercontent.com/71798557/120904043-95562200-c652-11eb-8a31-97b736204308.jpg)

**Comment by Zeus64** [comment]
Thanks Svema-svg, I just updated Update.bat and also dx.bat

**Comment by Svema-svg** [comment]
я проверю немного позже и напишу вам, у меня сейчас ночь и надо спать
I'll check a little later and write to you, I have a night now and need to sleep

**Comment by Svema-svg** [comment]
oh, yes, super, now Update.bat copies and GIT patches files well and without errors.
---------------------
Now GIT knows exactly where the files are and so everything goes well:

echo Path the source code
CHDIR ".\..\..\..\"
git apply --ignore-space-change --ignorewhitespace .\embarcadero\sydney\10_4_2\sydney_10_4_2.patch -v
IF ERRORLEVEL 1 goto ERROR
CHDIR "%ProjectDir%"
echo.
---------------------
![2](https://user-images.githubusercontent.com/71798557/120906582-5e3c3c80-c663-11eb-8cb8-8c4602c859ec.jpg)

**Comment by Svema-svg** [comment]
but with the dx file.bat still has problems with paths

**Comment by Svema-svg** [comment]
----------------------------------------
But with the dx.bat still has problems with paths

**Comment by Svema-svg** [comment]
I'm sorry, but I speak very little English

**Comment by Zeus64** [comment]
yes unfortunately dx.bat must be edited manually, their is no other way :(

**Comment by Svema-svg** [comment]
there is no way to determine the paths where other people have a component and where their sdk is located?

**Comment by Svema-svg** [comment]
![3](https://user-images.githubusercontent.com/71798557/120907179-21267900-c668-11eb-881b-7a97d95322b2.jpg)

**Comment by Svema-svg** [comment]
do no global variables contain the path to the component and to the sdk?

**Comment by Svema-svg** [comment]
if it is really not possible to find out the path to the component and to the sdk, then it is necessary to focus on this in the instructions for installing the component, something like:
you must manually open the dx.bat file (which is located in: ...\tools\D8Proxy\dx.bat) and specify your correct paths here:
![222](https://user-images.githubusercontent.com/71798557/120907593-892a8e80-c66b-11eb-8d14-683b7a9538bc.jpg)

**Comment by Svema-svg** [comment]
For me for example it looks like this:
![33](https://user-images.githubusercontent.com/71798557/120908364-3dc7ae80-c672-11eb-9972-ed30aae4824a.jpg)

**Comment by Zeus64** [comment]
Yes thanks for hall Svema-svg I will try to update the documentation!

**Comment by Svema-svg** [comment]
Thank you for a good and very useful component.

**Comment by Svema-svg** [comment]
WebRTC in delphi is very cool))

**Comment by manuelspataro** [comment]
Hi,
I followed all the installation instructions and read the posts, I have update  dx.bat but I have a compilation error on Android 32/64 bit:
[Exec Error] The command "PATH C: \ Program Files \ AdoptOpenJDK \ jdk-8.0.242.08-hotspot \ bin; C: \ Program Files \ AdoptOpenJDK \ jdk-8.0.242.08-hotspot \ bin; D: \ RadStudio_10.4.2 \ bin; D: \ RadStudio_10.4.2 \ bin64; C: \ Users \ Public \ Documents \ Embarcadero \ Studio \ 21.0 \ Bpl; C: \ Users \ Public \ Documents \ Embarcadero \ Studio \ 21.0 \ Bpl \ Win64; C: \ Program Files \ Common Files \ Microsoft Shared \ Windows Live; C: \ Program Files (x86) \ Common Files \ Microsoft Shared \ Windows Live; C: \ WINDOWS \ system32; C: \ WINDOWS; C: \ WINDOWS \ System32 \ Wbem; C: \ WINDOWS \ System32 \ WindowsPowerShell \ v1.0 \; C: \ Program Files (x86) \ Windows Live \ Shared; C: \ WINDOWS \ System32 \ OpenSSH \; C: \ App Maker \ Source \ Projects \ Lib \ Win32 \ Release; D: \ Embarcadero \ Windows Kits \ 10 \ Windows Performance Toolkit \; C: \ Users \ Public \ Embarcadero \ Studio \ 21.0 \ Bpl; C: \ Users \ ibc \ AppData \ Local \ Microsoft \ WindowsApps ; & set JAVA_HOME = C: \ Program Files \ AdoptOpenJDK \ jdk-8.0.242.08-hotspot & "C: \ Users \ Public \ Documents \ Embarcadero \ Studio \ 21.0 \ CatalogRepository \ AndroidSDK-2525-21.0.40680.4203 \ build-tools \ 29.0.3 \ dx .bat "--dex --output =" C: \ Temp \ alcinoe-master \ demos \ ALLiveVideoChat \ client \ Android \ Debug \ alcinoe-webrtc-dexed.jar "" C: \ Temp \ alcinoe-master \ lib \ jar \ com.alcinoe \ com.alcinoe.webrtc \ alcinoe-webrtc.jar "" exited with code 255.

Can you help me ?
